eachComponentDo: Robustness: Minor: Complain when no COMPONENT-DIR is passed
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/eachComponentDo b/bin/eachComponentDo
--- a/bin/eachComponentDo
+++ b/bin/eachComponentDo
@@ -41,6 +41,12 @@ do
 	*)		break;;
     esac
 done
+if [ $# -eq 0 ]; then
+    echo 'ERROR: No COMPONENT-DIR(s) passed.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 
 setupPythonVirtualEnv() {
     local projectDirspec="${1:?}"; shift
