ENH: Allow checkout of optional dependencies via include-optional-dependencies flag
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/extractGitDependencies b/bin/extractGitDependencies
--- a/bin/extractGitDependencies
+++ b/bin/extractGitDependencies
@@ -6,16 +6,29 @@ printUsage()
 Extract dependencies listed in the passed MARKDOWN-FILE(s).
 HELPTEXT
     echo
-    printf 'Usage: %q %s\n' "$(basename "$1")" 'MARKDOWN-FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--include-optional] [--] MARKDOWN-FILE [...] [-?|-h|--help]'
 }
 
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-esac
+typeset -a optionalFilter=(-e '/ (optional)\([[:space:]]\|$\)/d')
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+	--include-optional)
+			shift; optionalFilter=();;
+	--)		shift; break;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		break;;
+    esac
+done
 if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
 
-exec sed -n -e '/^#\+ Dependencies$/,/^#\+ /{ s#^\* \[[^]]\+\](\([^)]\+\))\([[:space:]].*\)\?$#\1#p; }' \
+exec sed -n \
+    -e '/^#\+ Dependencies$/,/^#\+ /{' \
+    "${optionalFilter[@]}" \
+    -e 's#^\* \[[^]]\+\](\([^)]\+\))\([[:space:]].*\)\?$#\1#p' \
+    -e '}' \
     -- "$@"
