runTests: UI: DWIM: Don't output error on no tests/COMPONENT-DIR(s) when checking
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/runTests b/bin/runTests
--- a/bin/runTests
+++ b/bin/runTests
@@ -12,6 +12,7 @@ HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" "[--check] [--exit-on-failure] [-c|--command \"ADDITIONAL-COMMANDLINE\" [-c ...] | --exec ADDITIONAL-SIMPLECOMMAND [...] ${EACHCOMPONENTDO_EXEC_END} [--exec ...]] [--] [COMPONENT-DIR [...]] [-?|-h|--help]"
 }
 
+isCheck=
 typeset -a runTestsInArgs=()
 typeset -a eachComponentDoArgs=()
 typeset -a eachComponentDoImplicitArgs=()
@@ -19,7 +20,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-	--check)	runTestsInArgs+=("$1"); shift; eachComponentDoImplicitArgs+=(--quiet --no-setup);;
+	--check)	runTestsInArgs+=("$1"); shift; eachComponentDoImplicitArgs+=(--quiet --no-setup); isCheck=t;;
 	--)		eachComponentDoArgs+=("$1"); shift; break;;
 	*)		eachComponentDoArgs+=("$1"); shift;;
     esac
@@ -29,7 +30,7 @@ set -- "${eachComponentDoArgs[@]}" "$@"
 if [ $# -eq 0 ]; then
     set -- tests/*
     if [ $# -eq 0 ]; then
-	echo >&2 'ERROR: No tests/COMPONENT-DIR(s) found.'
+	[ "$isCheck" ] || echo >&2 'ERROR: No tests/COMPONENT-DIR(s) found.'
 	exit 99
     fi
 fi
